Class {
	#name : #Something,
	#superclass : #Object,
	#category : #Somewhere
}

{ #category : #'as yet unclassified' }
Something >> afterOmmited [
]

{ #category : #'as yet unclassified' }
Something >> anthorAuthor [
]

{ #category : #'as yet unclassified' }
Something >> change [
]

{ #category : #'as yet unclassified' }
Something >> change1 [
]

{ #category : #'as yet unclassified' }
Something >> from2 [
]

{ #category : #'as yet unclassified' }
Something >> outoforder [
]

{ #category : #'as yet unclassified' }
Something >> outoforderwe [
]

{ #category : #'as yet unclassified' }
Something >> skip [
]

{ #category : #'as yet unclassified' }
Something >> skipqwe [
]
